# config/routes.yaml

index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

shop_index:
  path: /shop
  controller: App\Controller\ShopController::index
  requirements:
    _locale: "%app.supported_locales%"

shop_department:
  path: /shop/department/{categoryId}
  controller: App\Controller\ShopController::department
  methods: GET|HEAD
  requirements:
    _locale: "%app.supported_locales%"

cart_index:
  path: /cart
  controller: App\Controller\CartController::index
  requirements:
    _locale: "%app.supported_locales%"

contact_index:
  path: /contact
  controller: App\Controller\ContactController::index
  requirements:
    _locale: "%app.supported_locales%"
