# config/routes.yaml

index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

user_index:
  path: /user
  controller: App\Controller\UserController::index
  requirements:
    _locale: "%app.supported_locales%"

user_new:
  path: /user/new
  controller: App\Controller\UserController::new
  requirements:
    _locale: "%app.supported_locales%"

shop_index:
  path: /shop
  controller: App\Controller\ShopController::index
  requirements:
    _locale: "%app.supported_locales%"

shop_department:
  path: /shop/department/{categoryId}
  controller: App\Controller\ShopController::department
  methods: GET|HEAD
  requirements:
    _locale: "%app.supported_locales%"

cart_index:
  path: /cart
  controller: App\Controller\CartController::index
  requirements:
    _locale: "%app.supported_locales%"

cart_add:
  path: /cart/add/{productId}/{quantity}
  controller: App\Controller\CartController::add
  requirements:
    _locale: "%app.supported_locales%"

cart_remove:
  path: /cart/remove/{productId}/{quantity}
  controller: App\Controller\CartController::remove
  requirements:
    _locale: "%app.supported_locales%"

cart_delete:
  path: /cart/delete/{productId}
  controller: App\Controller\CartController::delete
  requirements:
    _locale: "%app.supported_locales%"

cart_validation:
  path: /cart/validation
  controller: App\Controller\CartController::validation
  requirements:
    _locale: "%app.supported_locales%"

contact_index:
  path: /contact
  controller: App\Controller\ContactController::index
  requirements:
    _locale: "%app.supported_locales%"
