# config/routes.yaml

index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

shop:
  path: /shop
  controller: App\Controller\shopController::shop
  requirements:
    _locale: "%app.supported_locales%"
