# config/routes.yaml

index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

shop:
  path: /shop
  controller: App\Controller\ShopController::index
  requirements:
    _locale: "%app.supported_locales%"

department:
  path: /shop/{categoryId}
  controller: App\Controller\ShopController::department
  requirements:
    _locale: "%app.supported_locales%"

cart:
  path: /cart
  controller: App\Controller\CartController::index
  requirements:
    _locale: "%app.supported_locales%"

contact:
  path: /contact
  controller: App\Controller\ContactController::index
  requirements:
    _locale: "%app.supported_locales%"
