index:
  path: /
  controller: App\Controller\DefaultController::index
# config/routes.yaml

# hello_page:
#   path: /hello/{userName}
#   controller: App\Controller\DefaultController::hello
#   defaults:
#     userName: "Anonyme"
